---
elk_version:

elk_base_dir: 

elk_elasticsearch_container_name:
elk_kibana_container_name: 
elk_logstash_container_name: 

elk_elasticsearch_port: 
elk_kibana_port: 
elk_logstash_port: 
elk_logstash_beats_port: 

elk_elasticsearch_java_opts: 

elk_elastic_password: 

elk_kibana_service_token_name:
elk_kibana_service_token_file:

elk_network_name:

elk_elasticsearch_data_dir:

elk_restart_policy:
